projectsite/urls.py
from django.urls import path
from django.views.generic import TemplateView
from projectsite import views

urlpatterns = [

    # Dashboard URLs
    path('manage_projects/', views.manage_projects, name='manage_projects'),
    path('admin_dashboard/',views.admin_dashboard_view,name='admin_dashboard'),
    

    # Success and Status Update URLs
    path('status-update/<int:project_id>/', views.status_update_view, name='status_update'),
    path('success/', TemplateView.as_view(template_name='projectsite/success.html'), name='success'),

    # Project URLs
    path('project/<int:project_id>/', views.project_details, name='project_details'),
    path('projects/add/', views.project_add_view, name='project_add'),
    path('projects/client/<int:client_id>/', views.project_list_by_client, name='project_list_by_client'),
    path('project/<int:project_id>/edit/', views.project_edit_view, name='project_edit'),
    path('project/<int:project_id>/delete/', views.project_delete_view, name='project_delete'),
    path('projects/', views.project_list, name='project_list'),

    # Stage URLs
    path('project/<int:project_id>/stages/', views.stage_list, name='stage_list'),
    path('project/<int:project_id>/stage/<int:stage_id>/', views.stage_details, name='stage_details'),
    path('project/<int:project_id>/stages/add/', views.stage_create, name='stage_add'),
    path('stage/<int:stage_id>/edit/', views.stage_edit, name='stage_edit'),
    path('stage/<int:stage_id>/delete/', views.stage_delete, name='stage_delete'),
    path('stage_list/<int:project_id>/', views.stage_list, name='stage_list'),
    path('project/<int:project_id>/stages/', views.stages_list_by_client, name='stages_list_by_client'),

    # Expense URLs
    path('projects/<int:project_id>/expenses/', views.expense_list, name='expense_list'),
    path('projects/<int:project_id>/expenses/new/', views.expense_new, name='expense_new'),
    path('projects/<int:project_id>/expenses/<int:expense_id>/', views.expense_details, name='expense_details'),
    path('projects/<int:project_id>/expenses/<int:expense_id>/edit/', views.expense_edit, name='expense_edit'),
    path('projects/<int:project_id>/expenses/<int:expense_id>/delete/', views.expense_delete, name='expense_delete'),

    
]



trackproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('site/',include('projectsite.urls')),
    path('',include('frontsite.urls')),
    path('user/',include('user.urls')),
  
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

admin.site.site_header="Leaf Construction "
admin.site.site_title='Browser Title'
admin.site.index_title ="Welcome to Construction Project....."

urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('site/',include('projectsite.urls')),
    path('',include('frontsite.urls')),
    path('user/',include('user.urls')),
  
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

admin.site.site_header="Leaf Construction "
admin.site.site_title='Browser Title'
admin.site.index_title ="Welcome to Construction Project....."

projectsite/models.py
from django.db import models
from frontsite.models import CustomUser
from django.contrib.auth.models import User
from django.conf import settings  # Import the settings module
from decimal import Decimal


class Project(models.Model):
    STATUS_CHOICES = [
        ('not_started', 'Not Started'),
        ('in_progress', 'In Progress'),
        ('completed', 'Completed'),
        ('on_hold', 'On Hold'),
    ]

    client = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='projects',null=True)
    
    name = models.CharField(max_length=100)
    budget = models.DecimalField(max_digits=10, decimal_places=2)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='not_started')
    length = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True, verbose_name="Length (feet)")
    breadth = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True, verbose_name="Breadth (feet)")
    land_area = models.DecimalField(max_digits=10, decimal_places=2, null=True, verbose_name="Total Land Area (sq ft)")
    
    def save(self, *args, **kwargs):
       
        # Dynamically calculate total land area if length and breadth are provided
        if self.length and self.breadth:
            self.land_area = Decimal(self.length) * Decimal(self.breadth)
            # Ensure precision to 2 decimal places
            self.land_area = self.land_area.quantize(Decimal('0.01'))
 
        super().save(*args, **kwargs)


    def __str__(self):
        return self.name

    def update_status(self):
        """
        Dynamically updates the status of the project based on its related stages.
        """
        # Check related stages
        if self.stages.filter(status='in_progress').exists():
            self.status = 'in_progress'
        elif self.stages.filter(status='not_started').exists():
            self.status = 'not_started'
        elif self.stages.filter(status='on_hold').exists():
            self.status = 'on_hold'
        elif self.stages.filter(status='completed').count() == self.stages.count():
            self.status = 'completed'
        else:
            self.status = 'not_started'

        # Save the updated status
        self.save()



class Stage(models.Model):
    STAGE_CHOICES = [
        ('ceiling', 'Ceiling'),
        ('flooring', 'Flooring'),
        ('plumbing', 'Plumbing'),
        ('painting', 'Painting'),
        ('foundation', 'Foundation'),
        ('framing', 'Framing'),
        ('electrical', 'Electrical'),
        ('hvac', 'HVAC'),
        ('roofing', 'Roofing'),
        ('drywall', 'Drywall'),
        ('insulation', 'Insulation'),
        ('siding', 'Siding'),
        ('windows', 'Windows'),
        ('doors', 'Doors'),
        ('landscaping', 'Landscaping'),
        ('finishing', 'Finishing'),
        ('furniture_installation', 'Furniture Installation'),
        ('final_touchups', 'Final Touch-ups')
    ]
  
    STATUS_CHOICES = [
        ('not_started', 'Not Started'),
        ('in_progress', 'In Progress'),
        ('completed', 'Completed'),
        ('on_hold', 'On Hold'),
    ]
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='stages')
    name = models.CharField(max_length=100)
    due_date = models.DateField()
    start_date = models.DateField()
    end_date = models.DateField(null=True, blank=True)
    progress = models.IntegerField(default=0)  # Percentage progress
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='not_started')
    stage_type = models.CharField(max_length=50, choices=STAGE_CHOICES)
    def __str__(self):
        return f"{self.name} - {self.project.name}"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)  # Save stage instance
        # Update project status
        self.project.update_status()
    


class Expense(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE,related_name='expenses', verbose_name="Project")
    stage = models.ForeignKey(Stage, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="Stage")
    amount_spent = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Amount Spent")
    date = models.DateField(verbose_name="Date")

    class Meta:
        ordering = ['date']
        verbose_name = "Expense"
        verbose_name_plural = "Expenses"

    def __str__(self):
        return f"{self.date} - {self.project.name} - {self.stage.stage_type if self.stage else 'No Stage'}"

projectsite/forms.py
from django import forms
from .models import  Project, Stage, Expense
from frontsite.models import CustomUser
from decimal import Decimal
from datetime import date



class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['client', 'name', 'budget', 'length', 'breadth', 'status']  
        widgets = {
            'client': forms.Select(attrs={'class': 'form-control'}),
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter project name'}),
            'budget': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter budget'}),
            'length': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter length in feet'}),  
            'breadth': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter breadth in feet'}),
            'status': forms.Select(attrs={'class': 'form-control'}),
        }
 


class StageForm(forms.ModelForm):
    class Meta:
        model = Stage
        fields = ['project', 'name', 'due_date', 'progress', 'status', 'start_date', 'end_date', 'stage_type']
        widgets = {
            'project': forms.Select(attrs={'class': 'form-control'}),
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter stage name'}),
            'due_date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'progress': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter progress percentage'}),
            'status': forms.Select(attrs={'class': 'form-control'}),
            'start_date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'end_date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'stage_type': forms.Select(attrs={'class': 'form-control'}),
        }
    def clean_start_date(self):
        start_date = self.cleaned_data.get('start_date')
        if start_date < date.today():
            raise forms.ValidationError("Start date cannot be earlier than today's date.")
        return start_date



class ExpenseForm(forms.ModelForm):
    class Meta:
        model = Expense
        fields = ['project', 'stage',  'amount_spent', 'date']
        widgets = {
            'project': forms.Select(attrs={'class': 'form-control', 'autocomplete': 'off'}),
            'stage': forms.Select(attrs={'class': 'form-control', 'autocomplete': 'off'}),
            'amount_spent': forms.NumberInput(attrs={'class': 'form-control', 'autocomplete': 'off'}),
            'date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date', 'autocomplete': 'off'}),
        }

templates/projectsite/stage/stage_add.html
{% extends 'projectsite/base.html' %}
{% block title %}Add Stage{% endblock %}
{% block content %}

           

<div class="container-fluid create well table-responsive p-4" style="margin-left:25em ;width:632px;margin-top:4em">
    <div class="container">
        <form method="post">
            {% csrf_token %}
        <div class="row mb-3">
            <label for="id_project" class="col-12 col-md-3 col-form-label">Project:</label>
            <div class="col-12 col-md-9">
              {{ form.project }}
            </div>
          </div>
          <div class="row mb-3">
            <label for="id_name" class="col-12 col-md-3 col-form-label">Name:</label>
            <div class="col-12 col-md-9">
              {{ form.name }}
            </div>
          </div>
          <div class="row mb-3">
            <label for="id_due_date" class="col-12 col-md-3 col-form-label">Due Date:</label>
            <div class="col-12 col-md-9">
              {{ form.due_date }}
            </div>
          </div>
          
          <div class="row mb-3">
            <label for="id_start_date" class="col-12 col-md-3 col-form-label">start_date:</label>
            <div class="col-12 col-md-9">
              {{ form.start_date }}
            </div>
          </div>
          <div class="row mb-3">
            <label for="id_end_date" class="col-12 col-md-3 col-form-label">end_date:</label>
            <div class="col-12 col-md-9">
              {{ form.end_date }}
            </div>
          </div>
          <div class="row mb-3">
            <label for="id_progress" class="col-12 col-md-3 col-form-label">progress:</label>
            <div class="col-12 col-md-9">
              {{ form.progress }}
            </div>
          </div>
          <div class="row mb-3">
            <label for="id_status" class="col-12 col-md-3 col-form-label">status:</label>
            <div class="col-12 col-md-9">
              {{ form.status }}
            </div>
          </div>
          <div class="row mb-3">
            <label for="id_stage_type" class="col-12 col-md-3 col-form-label">stage_type:</label>
            <div class="col-12 col-md-9">
              {{ form.stage_type }}
            </div>
          </div>
          
          <button type="submit" class="btn btn-success">Save</button>
          <a href="{% url 'stage_list' project.id %}" class="btn btn-secondary">Cancel</a>
      </form>
</div>
</div>
<script>
    const new_date =new Date().toISOString().split('T')[0]
    document.getElementById('id_start_date').setAttribute('min',new_date)
    document.getElementById('id_end_date').setAttribute('min',new_date)
    const due_date =new Date().toISOString().split('T')[0]
    document.getElementById('id_due_date').setAttribute('min',due_date)
</script>
{% endblock %}

templates/projectsite/stage/stage_delete.html
{% extends 'projectsite/base.html' %}
{% block title %}Delete Stage{% endblock %}
{% block content %}
<div class="container mt-5 d-flex flex-column align-items-center">
    <div class="content-section text-center w-100"style="margin-left:16em; margin-top:5em;width:1150px">
    <h1>Delete Stage: {{ stage.name }}</h1>
    <p>Are you sure you want to delete this stage?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Delete</button>
        <a href="{% url 'stage_list' stage.project.id %}" class="btn btn-secondary">Cancel</a>
    </form>
    </div>
    </div>
{% endblock %}

templates/projectsite/stage/stage_details.html
{% extends 'projectsite/base.html' %}
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% block content %}

<div class="table-responsive"style="margin-left:16em; margin-top:5em;width:1150px">
    <h1 class="mb-4">Stage Details: {{ stage.name }}</h1> <!-- Display the project name from the first stage object -->
<table class="table table-striped table-bordered">
    <tr>
        <td><strong>Project</strong></td>
        <td>{{ stage.project.name }}</td>
    </tr>
    <tr>
        <td><strong>Stage Type</strong></td>
        <td>{{ stage.get_stage_type_display }}</td>
    </tr>
    <tr>
        <td><strong>Progress</strong></td>
        <td>{{ stage.progress }}%</td>
    </tr>
    <tr>
        <td><strong>Status</strong></td>
        <td>{{ stage.get_completed_display }}</td>
    </tr>
    <tr>
        <td><strong>Due Date</strong></td>
        <td>{{ stage.due_date }}</td>
    </tr>
    <tr>
        <td><strong>Start Date</strong></td>
        <td>{{ stage.start_date }}</td>
    </tr>
    <tr>
        <td><strong>End Date</strong></td>
        <td>{{ stage.end_date|default:"N/A" }}</td>
    </tr>
    <tr>
        <td><strong>Description</strong></td>
        <td>{{ stage.name }}</td>
    </tr>
    <td><a href="{% url 'stage_edit' stage.id %}" class="btn btn-warning btn-sm ms-1">Update</a>
    <a href="{% url 'stage_delete' stage.id %}" class="btn btn-danger btn-sm ms-1">Delete</a>
    <a href="{% url 'expense_list' project.id %}" class="btn btn-success btn-sm ms-2">Expenses</a>
        
     </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<a href="{% url 'stage_add' project.id %}" class="btn btn-primary">Add New Stage</a>
</div>
{% endblock %}

  
        

templates/projectsite/stage/stage_edit.html
{% extends 'projectsite/base.html' %}
{% block title %}Edit Stage{% endblock %}
{% block content %}
<div class="container-fluid create well table-responsive p-4" style="margin-left:25em ;width:632px;margin-top:4em">
    <div class="container">
    <h1>{{ form.instance.id|yesno:"Edit Stage,Add Stage" }}</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Save</button>
    </form>
    </div>
    </div>
{% endblock %}

templates/projectsite/stage/stage_list.html
{% extends 'projectsite/base.html' %}
{% block title %}Stage List{% endblock %}
{% block content %}

<div class="table-responsive"style="margin-left:16em; margin-top:5em;width:1150px">
   
    <h1>Stages for Project: {{ project.name }}</h1>
    <table class="table table-striped table-bordered table-hover" style="width: 750px; text-align:center;">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Type</th>
                        <th>Progress</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for stage in stages %}
                    <tr>
                        <td>{{ stage.name }}</td>
                        <td>{{ stage.get_stage_type_display }}</td>
                        <td>{{ stage.progress }}%</td>
                        <td>
                            <a href="{% url 'stage_edit' stage.id %}" class="btn btn-warning btn-sm">Update</a>
                            <a href="{% url 'expense_list' project.id %}" class="btn btn-success btn-sm">Expenses</a>
                        
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="4" class="text-center">No stages found for this project.</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <a href="{% url 'stage_add' project.id %}" class="btn btn-success">Add New Stage</a>
        </div>
        
        
        {% endblock %}
        
                    
             

templates/projectsite/stage/stage_list_by_client.html
{% extends 'projectsite/base.html' %}
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block title %}Projects for {{ client.name }}{% endblock %}

{% block content %}

<div class="table-responsive"style="margin-left:16em; margin-top:5em;width:1150px">
   
    <h1>Projects for {{ client.name }}</h1>
    <table class="table table-striped" style="width: 850px;">
        <thead>
            <tr>
                <th>Name</th>
                <th>Budget</th>
                <th>Description</th>
                <th>View Stages</th> <!-- Add this line -->
            </tr>
        </thead>
        <tbody>
            {% for project in projects %}
            <tr>
                <td>{{ project.name }}</td>
                <td>{{ project.budget }}</td>
                <td>{{ project.description }}</td>
                <td>
                    <a href="{% url 'stages_list_by_project' project.id %}" class="btn btn-success btn-sm p-2">View Stages</a> <!-- Add this section -->
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'project_add' %}" class="btn btn-primary mt-3">Add New Project</a>
    <a href="{% url 'project_list' %}" class="btn btn-secondary mt-3">Back to Project List</a>
    </div>
   
{% endblock %}